### ISSUE TITLE
Présentation Onyxia / datalab

### ISSUE THREAD

**Issue by fcomte** [blue-hats/journee-bluehats-osx-2021#1]
Coté Insee, nous pourrions présenter le projet de plateforme de datascience : 

https://github.com/InseeFrLab/onyxia-web
https://github.com/InseeFrLab/onyxia

Il s'agit d'un projet opensource instanciable sur un cluster kubernetes qui vise à s'adresser à un datascientist ou à une équipe de datascientist pour lui fournir un environnement de travail confortable.

Nous maintenons également une plateforme en ligne ouverte à tous les agents de l'état à des fins de formations ou de travail sur données ouvertes : 
https://datalab.sspcloud.fr

**Comment by bzg** [comment]
Merci beaucoup !  J'ai ajouté une note dans le `README`.

**Comment by bzg** [comment]
Je me permets de clore cette issue, le contenu ayant été ajouté au programme.
